### ISSUE TITLE
Error: Evaluation failed: ReferenceError: identifyCrossFrames is not defined

### ISSUE THREAD

**Issue by dougkoellmer** [markusmobius/nodeSavePageWE#3]
I am not very experienced with Node, so apologies if this is something simple. It seems the functions in `nodeSavePageWE_client.js` are not being pulled in for evaluation? Any advice on how to incorporate your work into an existing Node app? Thank you very much for your work here. :)

**Comment by dougkoellmer** [comment]
Hmm it seems related to me loading a local `.mht` file into the WebView and not using an actual remote webpage. I will try to tinker here locally.

**Comment by markusmobius** [comment]
> I am not very experienced with Node, so apologies if this is something simple. It seems the functions in `nodeSavePageWE_client.js` are not being pulled in for evaluation? Any advice on how to incorporate your work into an existing Node app? Thank you very much for your work here. :)

The client code is not processed in Node but instead processed inside chromium instance of puppeteer - it measures everything on the page within the browser context and then pipes it back to Node. If you would call these functions from Node it would take a very long time because there is latency when Node communicates through puppeteer with the browser instance. So ideally you want to just communicate twice: first by injecting the client script into chromium and second by getting back the results.

There might be issues if you directly load an MHT file into Chromium. In other projects it sometimes didn't allow me to inject scripts when I loaded HTML directly into a page. What I had to do was first navigate to an external page (such as www.example.com) and then load the HTML.

**Comment by dougkoellmer** [comment]
Thank you for the reply. I figured out my problem but now it's another issue that is outside of your project's scope. Basically I can't use this approach with `.mht` files because of opaque security issues. I'm still trying some workarounds.

**Comment by markusmobius** [comment]
> Thank you for the reply. I figured out my problem but now it's another issue that is outside of your project's scope. Basically I can't use this approach with `.mht` files because of opaque security issues. I'm still trying some workarounds.

May I ask what you are trying to do? Are you trying to convert MHTML files to single file html? I am curious about your experience because I soon want to run a similar conversion. Do you have sample MHTML file? Was this file converted in IE or Chrome (I found that MHTML files from IE display quite differently on Chrome unfortunately).

**Comment by dougkoellmer** [comment]
Yes that's it exactly. The MHT file is created in Android WebView, so Chrome basically. I then want to create a plain HTML file with all assets embedded, images base-64ed, etc. A midway solution I have so far is to use https://pgm.bpalanka.com/mht2htm.html to convert the MHT to a folder with an "index" HTML document and all the assets like images, css, javascript as separate files. I then host these files temporarily on an internal/localhost-only server and point your module to the local address to create the single HTML file. The problem is that `mht2htm` can be really slow. Like even for this simple example I attached it can take many seconds. More than 10 or 15 sometimes. Your code is super fast, no problem there.

I think eventually I will simply write/port/modify a version of`mht2htm`that embeds the assets directly instead of creating separate files. At which point your code wouldn't even be needed.

Note I had to change the attachment extension from .mht to .txt so GitHub would accept it.

[28675.txt](https://github.com/markusmobius/nodeSavePageWE/files/5227137/28675.txt)
